### ISSUE TITLE
Transaction History

### ISSUE THREAD

**Issue by Maralai** [dvankley/firefly-plaid-connector-2#125]
I have successfully configured this connector and run the batch method to seed transactions from my various accounts. However, instead of the ~24 months (`maxSyncDays: 730`) of transactions I am expecting, I am only seeing 90 days. 

I have maxed out the maximum days and batch size per the Plaid API documentation. I am lost on how I can get this to pull earlier data.

```yml
fireflyPlaidConnector2:
  syncMode: ${SYNC_MODE:polled}
  useNameForDestination: true
  timeZone: America/Indianapolis
  transferMatchWindowDays: 3
  polled:
    syncFrequencyMinutes: 120
    existingFireflyPullWindowDays: 5
    cursorFileDirectoryPath: /opt/fpc-cursors
    allowItemToFail: false
  batch:
    maxSyncDays: 730
    setInitialBalance: false
  firefly:
    url: ${FIREFLY_URL}
    personalAccessToken: ${FIREFLY_ACCESS_TOKEN}
  plaid:
    url: ${PLAID_URL}
    clientId: ${PLAID_CLIENT_ID}
    secret: ${PLAID_SECRET}
    batchSize: 500
    maxRetries: 5
  descriptionExpression: "transaction.originalDescription ?: transaction.merchantName ?: transaction.name"
  categorization:
    primary:
      enable: true
      prefix: "p-"
    detailed:
      enable: true
      prefix: "d-"
  accounts: [redacted]
  product:
    name: Firefly Plaid Connector 2
logging:
  level:
    root: INFO
    net:
      djvk: DEBUG
```
