### ISSUE TITLE
cant find file after watchtower update

### ISSUE THREAD

**Issue by markwoodward86** [dvankley/firefly-plaid-connector-2#58]
Good day!

I just updated both fireflyiii-core and the plaid connector with a watchtower run and now the plaid connector will not start up. I get exit code 0 with the error 

`Caused by: java.io.FileNotFoundException: /opt/fpc-cursors/plaid_sync_cursors.txt (Permission denied)`

I have not changed anything else and have tried starting a new container from the latest image. I confirm that the filepath indeed does not exist (but it did not before either). Is there something different that i need to do to initiate this new image? The user does have write permissions to the opt directory.

Reverted to v1.0.8 and i am good again 👍

**Comment by dvankley** [comment]
What is the directory you're using to store the persistence file on your host machine? How have you set that as the value for HOST_PERSISTENCE_DIRECTORY_LOCATION in the environment docker compose uses? What are the permissions for that directory on your host machine?

This is the same symptom as https://github.com/dvankley/firefly-plaid-connector-2/issues/50 and your testing strongly points to it being an issue with the latest image. I haven't changed anything that should affect this stuff in the latest version, but a dependency update definitely could have.

**Comment by markwoodward86** [comment]
Thanks for the quick response. Permissions to my directory are full read write for the user. I performed a CHOWN o+x there again for good measure when testing yesterday before i reverted. Here is my compose file:

```
version: '3.8'

services:
  app:
    image: ghcr.io/dvankley/firefly-plaid-connector-2:v1.0.8
    restart: always
    volumes:
        - type: bind
          source: ~/plaid-connector-fireflyiii/firefly-plaid-connector-2/src/main/resources/application.yml
          target: /opt/fpc-config/application.yml
          read_only: true
        - type: bind
          source: ~/plaid-connector-fireflyiii/persistence
          target: /opt/fpc-cursors
    environment:
      - SPRING_CONFIG_LOCATION=/opt/fpc-config/application.yml
      - FIREFLYPLAIDCONNECTOR2_POLLED_CURSORFILEDIRECTORYPATH=/opt/fpc-cursors

volumes:
  fpc-cursors:

```
